### PR TITLE
Changed traget to target

### PR DESCRIPTION
**Pull request by eglute**
Changed a very small typo, from traget to target.

### CODE REVIEW

**Comment by yudai** [comment]
Thank you for submitting the PR.

Since this project is planned to be merged to the upstream repository,  CLA is required to contribute to this repository. Please see [contributer's guid](https://github.com/cloudfoundry/bosh/blob/master/CONTRIBUTING.md) for the detail. Let us know if you have already had a CLA with Pivotal.

**Comment by eglute** [comment]
Hello, I have emailed the signed CLA today. 
Thank you,
Egle

**Comment by jbayer** [comment]
I can confirm that the CLA is now on-file and ready to merge from that perspective.

**Comment by yudai** [comment]
Thanks @eglute and @jbayer! merged!

**Pull request merged**
